name: Test:TestResourceAccessor.testGetResources
run-name: Flaky Test
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip.exec=true -DretryFailedDeploymentCount=5
      - name: Test
        run: mvn test -pl helix-rest -Dtest=org.apache.helix.rest.server.TestResourceAccessor#testGetResources
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip.exec=true -DretryFailedDeploymentCount=5
      - name: Test
        run: mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl helix-rest -Dtest=org.apache.helix.rest.server.TestResourceAccessor#testGetResources
        
