name: Test:TestResourceAccessor.testGetResources
run-name: Flaky Test
on: [push]
jobs:
  Test_Without_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: mvn test -pl helix-rest -Dtest=org.apache.helix.rest.server.TestResourceAccessor#testGetResources
        
  Test_With_Nondex_Shuffling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Test
        run: mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl helix-rest -Dtest=org.apache.helix.rest.server.TestResourceAccessor#testGetResources
        
